package Capa_principal;

import capa_negocio.Caja;
import capa_negocio.Rol;
import capa_negocio.TipoDocumento;
import capa_negocio.Usuario;
import java.math.BigDecimal;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus
 */
public class jdManUsuario extends javax.swing.JDialog {

    TipoDocumento objTD = new TipoDocumento();
    Rol objR = new Rol();
    Caja objCa = new Caja();
    Usuario objU = new Usuario();

    public jdManUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        btnSexoUsuario.add(opMasculino);
        btnSexoUsuario.add(opFemenino);

        listarTipoDocumentos();
        listarRoles();
        listarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSexoUsuario = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        txtEmailUsuario = new javax.swing.JTextField();
        txtIDUsuario = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txtApPaternoUsuario = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        txtNumDocUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        opMasculino = new javax.swing.JRadioButton();
        opFemenino = new javax.swing.JRadioButton();
        jLabel65 = new javax.swing.JLabel();
        txtApMaternoUsuario = new javax.swing.JTextField();
        cboTipoDoc = new javax.swing.JComboBox<>();
        jdateFechaNacUsuario = new com.toedter.calendar.JDateChooser();
        jLabel66 = new javax.swing.JLabel();
        txtDireccionUsuario = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        txtCelularUsuario = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        txtSueldoUsuario = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        txtHorarioUsuario = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        cboRol = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        chkVigenciaUsuario = new javax.swing.JCheckBox();
        btnSimular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtFiltrarID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnDarBaja = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuaario");

        jPanel1.setBackground(new java.awt.Color(246, 244, 235));

        jPanel2.setBackground(new java.awt.Color(170, 215, 217));

        jLabel69.setBackground(new java.awt.Color(0, 0, 0));
        jLabel69.setText("Tipo Doc:");

        jLabel71.setBackground(new java.awt.Color(0, 0, 0));
        jLabel71.setText("Fecha Nac:");

        txtEmailUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtEmailUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmailUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailUsuarioKeyTyped(evt);
            }
        });

        txtIDUsuario.setEditable(false);
        txtIDUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtIDUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel62.setBackground(new java.awt.Color(70, 130, 169));
        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(51, 51, 51));
        jLabel62.setText("Datos del Usuario:");

        jLabel63.setBackground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("Nombre:");

        jLabel64.setBackground(new java.awt.Color(0, 0, 0));
        jLabel64.setText("Ap. Paterno:");

        jLabel67.setBackground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("ID usuario:");

        jLabel72.setBackground(new java.awt.Color(0, 0, 0));
        jLabel72.setText("Email:");

        txtApPaternoUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtApPaternoUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtApPaternoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApPaternoUsuarioKeyTyped(evt);
            }
        });

        jLabel73.setBackground(new java.awt.Color(0, 0, 0));
        jLabel73.setText("N° Documento:");

        txtNumDocUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtNumDocUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNumDocUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDocUsuarioKeyTyped(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtNombreUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyTyped(evt);
            }
        });

        jLabel74.setBackground(new java.awt.Color(0, 0, 0));
        jLabel74.setText("Sexo:");

        opMasculino.setBackground(new java.awt.Color(170, 215, 217));
        opMasculino.setText("Masculino");

        opFemenino.setBackground(new java.awt.Color(170, 215, 217));
        opFemenino.setText("Femenino");

        jLabel65.setBackground(new java.awt.Color(0, 0, 0));
        jLabel65.setText("Ap. Materno:");

        txtApMaternoUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtApMaternoUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtApMaternoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApMaternoUsuarioKeyTyped(evt);
            }
        });

        cboTipoDoc.setBackground(new java.awt.Color(239, 237, 220));

        jdateFechaNacUsuario.setBackground(new java.awt.Color(239, 237, 220));
        jdateFechaNacUsuario.setDateFormatString("yyyy-MM-dd");

        jLabel66.setBackground(new java.awt.Color(0, 0, 0));
        jLabel66.setText("Dirección:");

        txtDireccionUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtDireccionUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDireccionUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionUsuarioKeyTyped(evt);
            }
        });

        jLabel68.setBackground(new java.awt.Color(0, 0, 0));
        jLabel68.setText("N° Celular:");

        txtCelularUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtCelularUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCelularUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularUsuarioKeyTyped(evt);
            }
        });

        jLabel75.setBackground(new java.awt.Color(0, 0, 0));
        jLabel75.setText("Sueldo:");

        txtSueldoUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtSueldoUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSueldoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoUsuarioKeyTyped(evt);
            }
        });

        jLabel76.setBackground(new java.awt.Color(0, 0, 0));
        jLabel76.setText("Horario:");

        txtHorarioUsuario.setBackground(new java.awt.Color(239, 237, 220));
        txtHorarioUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtHorarioUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorarioUsuarioKeyTyped(evt);
            }
        });

        jLabel70.setBackground(new java.awt.Color(0, 0, 0));
        jLabel70.setText("Username:");

        txtUsername.setBackground(new java.awt.Color(239, 237, 220));
        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });

        jLabel77.setBackground(new java.awt.Color(0, 0, 0));
        jLabel77.setText("Contraseña:");

        txtContrasena.setBackground(new java.awt.Color(239, 237, 220));
        txtContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyTyped(evt);
            }
        });

        jLabel78.setBackground(new java.awt.Color(0, 0, 0));
        jLabel78.setText("Rol:");

        cboRol.setBackground(new java.awt.Color(239, 237, 220));

        jLabel1.setText("Estado :");

        chkVigenciaUsuario.setText("Vigente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel64)
                            .addComponent(jLabel67)
                            .addComponent(jLabel72)
                            .addComponent(jLabel69)
                            .addComponent(jLabel71)
                            .addComponent(jLabel66)
                            .addComponent(jLabel75)
                            .addComponent(jLabel73)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIDUsuario)
                                    .addComponent(txtApPaternoUsuario)
                                    .addComponent(txtEmailUsuario)
                                    .addComponent(cboTipoDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdateFechaNacUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccionUsuario)
                                    .addComponent(txtSueldoUsuario)
                                    .addComponent(txtNumDocUsuario))
                                .addGap(117, 117, 117)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel63)
                                    .addComponent(jLabel65)
                                    .addComponent(jLabel74)
                                    .addComponent(jLabel68)
                                    .addComponent(jLabel76)
                                    .addComponent(jLabel77)
                                    .addComponent(jLabel78)
                                    .addComponent(jLabel70))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(opMasculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(opFemenino))
                                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApMaternoUsuario)
                                    .addComponent(txtCelularUsuario)
                                    .addComponent(txtHorarioUsuario)
                                    .addComponent(txtContrasena)
                                    .addComponent(cboRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUsername)))
                            .addComponent(chkVigenciaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(361, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(362, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel62)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(txtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(txtApPaternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65)
                    .addComponent(txtApMaternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(txtDireccionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(txtCelularUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(txtEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74)
                    .addComponent(opMasculino)
                    .addComponent(opFemenino))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel75)
                    .addComponent(txtSueldoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76)
                    .addComponent(txtHorarioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(cboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78)
                    .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(txtNumDocUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel70)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel77)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdateFechaNacUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chkVigenciaUsuario))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(146, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );

        btnSimular.setBackground(new java.awt.Color(236, 177, 89));
        btnSimular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/simular.png"))); // NOI18N
        btnSimular.setText("SIMULAR DATOS");
        btnSimular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(246, 244, 235));

        jLabel23.setText("Buscar ID:");

        txtFiltrarID.setBackground(new java.awt.Color(204, 204, 204));
        txtFiltrarID.setBorder(null);
        txtFiltrarID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltrarIDKeyTyped(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(236, 177, 89));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lupa.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(236, 177, 89));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(236, 177, 89));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(236, 177, 89));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edity.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnDarBaja.setBackground(new java.awt.Color(236, 177, 89));
        btnDarBaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDarBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnDarBaja.setText("DAR DE BAJA");
        btnDarBaja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(txtFiltrarID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDarBaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFiltrarID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblUsuarios.setAutoCreateRowSorter(true);
        tblUsuarios.setBackground(new java.awt.Color(170, 215, 217));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblUsuarios.setShowGrid(false);
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblUsuarios);

        btnNuevo.setBackground(new java.awt.Color(236, 177, 89));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSimular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void limpiarFormulario() {
        txtFiltrarID.setText("");
        txtIDUsuario.setText("");
        txtNombreUsuario.setText("");
        txtApPaternoUsuario.setText("");
        txtApMaternoUsuario.setText("");
        txtDireccionUsuario.setText("");
        txtCelularUsuario.setText("");
        txtEmailUsuario.setText("");
        btnSexoUsuario.clearSelection();
        txtSueldoUsuario.setText("");
        txtHorarioUsuario.setText("");
        cboTipoDoc.setSelectedIndex(-1);
        txtNumDocUsuario.setText("");
        txtUsername.setText("");
        txtContrasena.setText("");
        jdateFechaNacUsuario.setDate(null);
        chkVigenciaUsuario.setSelected(false);
    }

    private void listarTipoDocumentos() {
        ResultSet rs = null;
        DefaultComboBoxModel modeloTipoDoc = new DefaultComboBoxModel();
        cboTipoDoc.setModel(modeloTipoDoc);

        try {
            rs = objTD.listarTodosTipoDoc();
            while (rs.next()) {
                modeloTipoDoc.addElement(rs.getString("tipo_doc"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los tipos de documentos");
        }
    }

    private void listarRoles() {
        ResultSet rs = null;
        DefaultComboBoxModel modeloRol = new DefaultComboBoxModel();
        cboRol.setModel(modeloRol);

        try {
            rs = objR.listarTodosRol();
            while (rs.next()) {
                modeloRol.addElement(rs.getString("rol"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los roles");
        }
    }

//    private void listarCajas() {
//        ResultSet rs = null;
//        DefaultComboBoxModel modeloCaja = new DefaultComboBoxModel();
//        cboCaja.setModel(modeloCaja);
//
//        try {
//            rs = objCa.listarTodosCaja();
//            while (rs.next()) {
//                modeloCaja.addElement(rs.getString("numero_caja"));
//            }
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, "Error al obtener las cajas");
//        }
//    }

    private void listarUsuarios() {
        ResultSet rs = null;
        String vigencia = "";

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Documento");
        modelo.addColumn("Nro. Documento");
        modelo.addColumn("Rol");
        modelo.addColumn("Nro. Caja que atiende");
        modelo.addColumn("Nombre Completo");
        modelo.addColumn("Fecha Nacimiento");
        modelo.addColumn("Dirección");
        modelo.addColumn("Celular");
        modelo.addColumn("Sexo");
        modelo.addColumn("Email");
        modelo.addColumn("Sueldo");
        modelo.addColumn("Horario");
        modelo.addColumn("Username");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Estado");
        modelo.addColumn("Último login");
        tblUsuarios.setModel(modelo);

        try {
            rs = objU.listarTodosUsuario();
            while (rs.next()) {
                //Esto depende si se actualiza según la tabla que mandó Burga
                if(rs.getString("estado").equals("t")){
                    vigencia = "Vigente";
                }else{
                    vigencia = "No Vigente";
                }
                
                Object[] fila = new Object[17];
                fila[0] = rs.getInt("id_usuario");
                fila[1] = rs.getString("tipo_doc");
                fila[2] = rs.getString("nro_documento");
                fila[3] = rs.getString("rol");
//                fila[4] = rs.getString("numero_caja");
                fila[4] = "cajita";
                fila[5] = rs.getString("nombre") + " " + rs.getString("ape_paterno") + " " + rs.getString("ape_materno");
                fila[6] = rs.getDate("fecha_nacimiento");
                fila[7] = rs.getString("direccion");
                fila[8] = rs.getString("nro_celular");
                fila[9] = rs.getString("sexo");
                fila[10] = rs.getString("email");
                fila[11] = rs.getString("sueldo");
                fila[12] = rs.getString("horario");
                fila[13] = rs.getString("username");
                fila[14] = rs.getString("contrasena");
                fila[15] = vigencia;
                fila[16] = rs.getTimestamp("ultimo_login");
                //fila[15] = rs.getTimestamp("ultimo_login");

                modelo.addRow(fila);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener los usuarios", "Ocurrió un error inesperado", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarUsuario() {
        ResultSet rs = null;

        try {
            if (txtFiltrarID.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese el ID del usuario", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int idUsuarioFiltro = Integer.parseInt(txtFiltrarID.getText());
                rs = objU.listarPorIDUsuario(idUsuarioFiltro);

                if (rs.next()) {
                    txtFiltrarID.setText(rs.getString("id_usuario"));
                    txtIDUsuario.setText(rs.getString("id_usuario"));
                    txtNombreUsuario.setText(rs.getString("nombre"));
                    txtApPaternoUsuario.setText(rs.getString("ape_paterno"));
                    txtApMaternoUsuario.setText(rs.getString("ape_materno"));
                    txtDireccionUsuario.setText(rs.getString("direccion"));
                    txtCelularUsuario.setText(rs.getString("nro_celular"));
                    txtEmailUsuario.setText(rs.getString("email"));
                    boolean sexo = rs.getBoolean("sexo");
                    if (sexo == true) {
                        opMasculino.setSelected(true);
                    } else {
                        opFemenino.setSelected(true);
                    }
                    txtSueldoUsuario.setText(rs.getString("sueldo"));
                    txtHorarioUsuario.setText(rs.getString("horario"));
                    cboTipoDoc.setSelectedIndex(rs.getInt("id_tipo_doc") - 1);
                    txtNumDocUsuario.setText(rs.getString("nro_documento"));
                    cboRol.setSelectedIndex(rs.getInt("id_rol") - 1);
                    //cboCaja.setSelectedIndex(rs.getInt("id_caja") - 1);
                    txtUsername.setText(rs.getString("username"));
                    txtContrasena.setText(rs.getString("contrasena"));

                    chkVigenciaUsuario.setSelected(rs.getBoolean("estado"));

                    jdateFechaNacUsuario.setDate(rs.getDate("fecha_nacimiento"));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar el usuario", "Ocurrió un error inesperado", JOptionPane.ERROR_MESSAGE);
        }
    }

    public boolean validarFecha(Date fechaNac) {
        Date fechaActual = new Date();
        if (fechaNac.after(fechaActual)) {
            return false;
        }
        return true;
    }

    private void ingresar() {
        try {
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");

            if (btnNuevo.getText().equals("NUEVO")) {
                btnNuevo.setText("GUARDAR");
                limpiarFormulario();
                opMasculino.setSelected(true);
                txtIDUsuario.requestFocus();

                int idU = objU.genenrarIDUsuario();
                txtIDUsuario.setText("" + idU);
            } else {
                Date fechaSeleccionada = jdateFechaNacUsuario.getDate();
                if (validarFecha(fechaSeleccionada) == false) {
                    JOptionPane.showMessageDialog(this, "Por favor ingrese una fecha válida", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    btnNuevo.setText("NUEVO");
                    String nombreTipoDoc = cboTipoDoc.getSelectedItem().toString();
                    String nombreRol = cboRol.getSelectedItem().toString();
                    //String numCaja = cboCaja.getSelectedItem().toString();

                    int idUsuario = Integer.parseInt(txtIDUsuario.getText());
                    String numDoc = txtNumDocUsuario.getText();
                    String nombre = txtNombreUsuario.getText();
                    String apPat = txtApPaternoUsuario.getText();
                    String apMat = txtApMaternoUsuario.getText();
                    String fechaNac = date.format(fechaSeleccionada);
                    String direccion = txtDireccionUsuario.getText();
                    String celular = txtCelularUsuario.getText();
                    float sueldo = Float.parseFloat(txtSueldoUsuario.getText());
                    String horario = txtHorarioUsuario.getText();
                    boolean sexo = opMasculino.isSelected();
                    boolean estado = chkVigenciaUsuario.isSelected();
                    String email = txtEmailUsuario.getText();
                    int tipoDoc = objTD.obtenerIDTipoDoc(nombreTipoDoc);
                    int rol = objR.obtenerIDRol(nombreRol);
                    //int caja = objCa.obtenerIDCaja(numCaja);

                    String username = txtUsername.getText();
                    String contrasena = txtContrasena.getText();

                    //objU.insertarUsuario(idUsuario, nombre, apPat, apMat, numDoc, fechaNac, direccion, celular, sexo, sueldo, horario, username, email, contrasena, rol, tipoDoc, caja);
                    objU.insertarUsuario(idUsuario, nombre, apPat, apMat, numDoc, fechaNac, direccion, celular, sexo, sueldo, horario, username, email, contrasena, rol, tipoDoc, estado);
                    
                    limpiarFormulario();
                    listarUsuarios();
                }

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar insertar el usuario", "Ocurrió un error inesperado", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void modificar() {
        try {
            if (txtIDUsuario.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese el ID del usuario", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else {
                SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
                int rpta = JOptionPane.showConfirmDialog(this, "¿Desea modificar la información de este usuario?", "Seleccione una opción", JOptionPane.YES_NO_OPTION);

                if (rpta == 0) {
                    Date fechaSeleccionada = jdateFechaNacUsuario.getDate();
                    if (validarFecha(fechaSeleccionada) == false) {
                        JOptionPane.showMessageDialog(this, "Por favor ingrese una fecha válida", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        String nombreTipoDoc = cboTipoDoc.getSelectedItem().toString();
                        String nombreRol = cboRol.getSelectedItem().toString();
                        //String numCaja = cboCaja.getSelectedItem().toString();

                        int idUsuario = Integer.parseInt(txtIDUsuario.getText());
                        String numDoc = txtNumDocUsuario.getText();
                        String nombre = txtNombreUsuario.getText();
                        String apPat = txtApPaternoUsuario.getText();
                        String apMat = txtApMaternoUsuario.getText();
                        String fechaNac = date.format(fechaSeleccionada);
                        String direccion = txtDireccionUsuario.getText();
                        String celular = txtCelularUsuario.getText();
                        float sueldo = Float.parseFloat(txtSueldoUsuario.getText());
                        String horario = txtHorarioUsuario.getText();
                        boolean sexo = opMasculino.isSelected();
                        boolean estado = chkVigenciaUsuario.isSelected();
                        String email = txtEmailUsuario.getText();
                        int tipoDoc = objTD.obtenerIDTipoDoc(nombreTipoDoc);
                        int rol = objR.obtenerIDRol(nombreRol);
                        //int caja = objCa.obtenerIDCaja(numCaja);

                        String username = txtUsername.getText();
                        String contrasena = txtContrasena.getText();

                        //objU.modificarUsuario(idUsuario, nombre, apPat, apMat, numDoc, fechaNac, direccion, celular, sexo, sueldo, horario, username, email, contrasena, rol, tipoDoc, caja);
                        objU.modificarUsuario(idUsuario, nombre, apPat, apMat, numDoc, fechaNac, direccion, celular, sexo, sueldo, horario, username, email, rol, tipoDoc, estado);

                        limpiarFormulario();
                        listarUsuarios();
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar modificar el usuario", "Ocurrió un error inesperado", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void eliminar() {
        try {
            if (txtIDUsuario.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese el ID del usuario", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int rpta = JOptionPane.showConfirmDialog(this, "¿Desea eliminar permanentemente la información de este usuario?", "Seleccione una opción", JOptionPane.YES_NO_OPTION);

                if (rpta == 0) {
                    int idUsuario = Integer.parseInt(txtIDUsuario.getText());
                    objU.eliminarUsuario(idUsuario);
                    limpiarFormulario();
                    listarUsuarios();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar eliminar el usuario", "Ocurrió un error inesperado", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void txtEmailUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailUsuarioKeyTyped
        // TODO add your handling code here:
        if (txtEmailUsuario.getText().length() >= 200) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmailUsuarioKeyTyped

    private void txtApPaternoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApPaternoUsuarioKeyTyped
        // TODO add your handling code here:
        int x = evt.getKeyChar();
        boolean validacion = x >= 65 && x <= 90 || x >= 97 && x <= 122;
        if (!validacion) {
            evt.consume();
        }

        if (txtApPaternoUsuario.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApPaternoUsuarioKeyTyped

    private int definirLimite() {
        String tipoDoc = cboTipoDoc.getSelectedItem().toString();
        int limite = 0;

        switch (tipoDoc) {
            case "DNI":
                limite = 8;
                break;
            case "Carné de Extranjería":
                limite = 12;
                break;
            case "Pasaporte":
                limite = 15;
                break;
        }

        return limite;
    }

    private void txtNumDocUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDocUsuarioKeyTyped
        // TODO add your handling code here:
        int limite = definirLimite();

        int x = evt.getKeyChar();
        boolean validacion = x >= 48 && x <= 57;
        if (!validacion) {
            evt.consume();
        }

        if (txtNumDocUsuario.getText().length() >= limite) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumDocUsuarioKeyTyped

    private void txtNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyTyped
        // TODO add your handling code here:
        int x = evt.getKeyChar();
        boolean validacion = x >= 65 && x <= 90 || x >= 97 && x <= 122;
        if (!validacion) {
            evt.consume();
        }

        if (txtNombreUsuario.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreUsuarioKeyTyped

    private void txtApMaternoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApMaternoUsuarioKeyTyped
        // TODO add your handling code here:
        int x = evt.getKeyChar();
        boolean validacion = x >= 65 && x <= 90 || x >= 97 && x <= 122;
        if (!validacion) {
            evt.consume();
        }

        if (txtApMaternoUsuario.getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApMaternoUsuarioKeyTyped

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed

    }//GEN-LAST:event_btnSimularActionPerformed

    private void txtFiltrarIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarIDKeyTyped
        // TODO add your handling code here:
        int x = evt.getKeyChar();
        boolean validacion = x >= 48 && x <= 57;
        if (!validacion) {
            evt.consume();
        }

        if (txtFiltrarID.getText().length() >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFiltrarIDKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarUsuario();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBajaActionPerformed

    }//GEN-LAST:event_btnDarBajaActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        txtIDUsuario.setText(String.valueOf(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0)));
        txtFiltrarID.setText(String.valueOf(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0)));
        btnBuscarActionPerformed(null);
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        ingresar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtDireccionUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionUsuarioKeyTyped
        // TODO add your handling code here:
        if (txtDireccionUsuario.getText().length() >= 200) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDireccionUsuarioKeyTyped

    private void txtCelularUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularUsuarioKeyTyped
        // TODO add your handling code here:
        int x = evt.getKeyChar();
        boolean validacion = x >= 48 && x <= 57;
        if (!validacion) {
            evt.consume();
        }

        if (txtCelularUsuario.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCelularUsuarioKeyTyped

    private void txtSueldoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoUsuarioKeyTyped
        // TODO add your handling code here:
        int x = evt.getKeyChar();
        boolean validacion = x >= 48 && x <= 57 || x == 46;
        if (!validacion) {
            evt.consume();
        }

        if (txtSueldoUsuario.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSueldoUsuarioKeyTyped

    private void txtHorarioUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorarioUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorarioUsuarioKeyTyped

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void txtContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDarBaja;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup btnSexoUsuario;
    private javax.swing.JButton btnSimular;
    private javax.swing.JComboBox<String> cboRol;
    private javax.swing.JComboBox<String> cboTipoDoc;
    private javax.swing.JCheckBox chkVigenciaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser jdateFechaNacUsuario;
    private javax.swing.JRadioButton opFemenino;
    private javax.swing.JRadioButton opMasculino;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApMaternoUsuario;
    private javax.swing.JTextField txtApPaternoUsuario;
    private javax.swing.JTextField txtCelularUsuario;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtDireccionUsuario;
    private javax.swing.JTextField txtEmailUsuario;
    private javax.swing.JTextField txtFiltrarID;
    private javax.swing.JTextField txtHorarioUsuario;
    private javax.swing.JTextField txtIDUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNumDocUsuario;
    private javax.swing.JTextField txtSueldoUsuario;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
